language: java
jdk:
- oraclejdk8
env:
  matrix:
  - IDEA_VERSION=15
  - IDEA_VERSION=16
install: "./gradlew extractIdeaSdk"
script: "./gradlew test dist -Pversion=${TRAVIS_TAG:-wip} && ls build/distributions"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VToIzl75WQc4GR37C1RMKIzdND5hDxfehSDfCnYGz1aHLMuw869QR+N2CHxfPtPept7XlE1SURyNbNn1BTN6KWCGqXtXi/qV0doa7UWmbnmEd9qNOtsYLsTjDlFNO9dU2DOTw9YC+be90BsIsmwtoE3bpM5eq78foZe0etYxMbTpgylBLFa4oCK373z59EwcbEWN+hXzU2kRJJgObUHYJwa9RDS3bhD1mAtdhA///DvBNuzVuCRnp/bsiLX4exbxvv4JU7DYF7Hu3dVfoHPMCFch4lO/2X5ge9+cqHSwsaEegpXnqshOaAVfD51iNAh1ENVxuV930dbtXGi8KENgMrwqADqvbWf1oK+sW8PN0LtAJLSiVm7B5TEZukfexmJOKYDRuG2RrIo8Pa+mDN9bhjbnDlionAp/ID0+++dfDb+sgu1PQi/sTx/Ni3y5kPfWD92upq5cxzJ0764HYc6z9IREXqTIfnujRxjVMAj3WsDkz3p2yg8SdSZ7mCxpmW+Isf5V8ha1SXkavejvBcntuEg7uBUIy/oNvpQvZqx4oOfBCk88JG2vwNRNUjJe6tWeZybCgn+mtgRLfe21EyyVLkIPELeGRZ5NTU0PGq5LdpHRGHj415rQx3ZervznLSh1+ixwg/fH9vusV2L03UX/r6S9tXLJaQaZ1ZgYH/K/dDo=
  file: build/distributions/idea-fitnesse-${TRAVIS_TAG}.zip
  on:
    repo: fitnesse/idea-fitnesse
    tags: true
    condition: $IDEA_VERSION = 15
sudo: false
cache:
  directories:
  - "$HOME/.gradle"
  - lib
